# Generated by Django 4.0.5 on 2022-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctorregister_auth_token_doctorregister_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='other_medication',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
