# Generated by Django 4.1.3 on 2022-11-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paindetails_mood_changed_paindetails_ways_relax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alone', models.CharField(blank=True, max_length=20, null=True)),
                ('martual_status', models.CharField(blank=True, max_length=20, null=True)),
                ('number_children', models.CharField(blank=True, max_length=20, null=True)),
                ('number_children_home', models.CharField(blank=True, max_length=20, null=True)),
                ('current_situtaion', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(blank=True, max_length=20, null=True)),
                ('stop_working', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_actions', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'personal_details',
            },
        ),
    ]
