# Generated by Django 4.1.3 on 2022-11-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_patientregister_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='reset_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
